# General
name: The Real Bojan
tagline: Find the real bojans!

# Jekyll
exclude: ['Rakefile']
markdown: redcarpet

# App Store
appstore_url: https://itunes.apple.com/app/id123456789
appstore: <a href="https://itunes.apple.com/app/id123456789" class="app-store" rel="external nofollow"><img src="/assets/app-store.svg" alt="Download on the App Store"></a>
appstore_white: <a href="https://itunes.apple.com/app/id123456789" class="app-store" rel="external nofollow"><img src="/assets/app-store-white.svg" alt="Download on the App Store"></a>

# Screenshots
screenshots:
- screen-shot-1
- screen-shot-2

# Company Info
company: The Real Bojan
company_website: https://vanderlin.github.io/the-real-bojan/

# Emails
email_press: real-bojan-app@gmail.com
email_contact: real-bojan-app@gmail.com
email_support: real-bojan-app@gmail.com
